# Generated by Django 3.2.7 on 2021-09-07 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('esameA', models.BooleanField(default=False, verbose_name='OFA')),
                ('esameB', models.BooleanField(default=False, verbose_name='Algebra lineare')),
                ('esameC', models.BooleanField(default=False, verbose_name='Analisi matematica')),
                ('esameD', models.BooleanField(default=False, verbose_name='Programmazione 1')),
                ('esameE', models.BooleanField(default=False, verbose_name='Inglese')),
                ('esameF', models.BooleanField(default=False, verbose_name='Algoritmi e strutture dati')),
                ('esameG', models.BooleanField(default=False, verbose_name='Architettura dei calcolatori')),
                ('esameH', models.BooleanField(default=False, verbose_name='Programmazione 2')),
                ('esameI', models.BooleanField(default=False, verbose_name='Fisica')),
                ('esameJ', models.BooleanField(default=False, verbose_name='Programmazione a oggetti')),
                ('esameK', models.BooleanField(default=False, verbose_name='Sistemi operativi')),
                ('esameL', models.BooleanField(default=False, verbose_name='Statistica ed elementi di probabilità')),
                ('esameM', models.BooleanField(default=False, verbose_name='Apprendimento ed evoluzione in sistemi artificiali')),
                ('esameN', models.BooleanField(default=False, verbose_name='Basi di dati')),
                ('esameO', models.BooleanField(default=False, verbose_name='Calcolo numerico')),
                ('esameP', models.BooleanField(default=False, verbose_name='Ottimizzazione lineare intera')),
                ('esameQ', models.BooleanField(default=False, verbose_name='Paradigmi e linguaggi di programmazione')),
                ('esameR', models.BooleanField(default=False, verbose_name='Protocolli e architettura di rete')),
                ('esameS', models.BooleanField(default=False, verbose_name='Tirocinio')),
                ('esameT', models.BooleanField(default=False, verbose_name='Prova finale')),
                ('esameU', models.BooleanField(default=False, verbose_name='Compilatori')),
                ('esame_fA', models.BooleanField(default=False, verbose_name='Algebra A')),
                ('esame_fB', models.BooleanField(default=False, verbose_name='Linguaggi dinamici')),
                ('esame_fC', models.BooleanField(default=False, verbose_name='Tecnologie web')),
                ('esame_fD', models.BooleanField(default=False, verbose_name='Progetto del software')),
                ('esame_fE', models.BooleanField(default=False, verbose_name="Gestione dell'informazione")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
