# Generated by Django 3.2.7 on 2021-09-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210912_1415'),
        ('users', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='esameA',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='esameB',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='esameC',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='esameD',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='esameE',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='esameF',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='esameG',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='esameH',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='esameI',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='esameJ',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='esameK',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='esameL',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='esameM',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='esameN',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='esameO',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='esameP',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='esameQ',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='esameR',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='esameS',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='esameT',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='esameU',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='esame_fA',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='esame_fB',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='esame_fC',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='esame_fD',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='esame_fE',
        ),
        migrations.AddField(
            model_name='profile',
            name='threads',
            field=models.ManyToManyField(related_name='user_thread', to='blog.Thread'),
        ),
    ]
