# Generated by Django 3.2.7 on 2021-09-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210908_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='karma',
            field=models.IntegerField(default=0),
        ),
    ]
