# Generated by Django 3.2.7 on 2021-09-09 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210909_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='newauthor',
            new_name='author',
        ),
    ]
