# Generated by Django 3.2.7 on 2021-09-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210912_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='periodo',
            field=models.CharField(choices=[('Secondo anno', 'Secondo anno'), ('Primo anno', 'Primo anno'), ('Facoltativi', 'Facoltativi'), ('Terzo anno', 'Terzo anno')], default='Primo anno', max_length=100),
        ),
    ]
