# Generated by Django 3.2.7 on 2021-09-12 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_thread_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_thread', to='blog.thread'),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_type', to='blog.type'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='periodo',
            field=models.CharField(choices=[('Primo anno', 'Primo anno'), ('Terzo anno', 'Terzo anno'), ('Secondo anno', 'Secondo anno'), ('Facoltativi', 'Facoltativi')], default='Primo anno', max_length=100),
        ),
    ]
