# Generated by Django 3.2.7 on 2021-09-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210912_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='karma',
        ),
        migrations.AlterField(
            model_name='thread',
            name='periodo',
            field=models.CharField(choices=[('Facoltativi', 'Facoltativi'), ('Primo anno', 'Primo anno'), ('Secondo anno', 'Secondo anno'), ('Terzo anno', 'Terzo anno')], default='Primo anno', max_length=100),
        ),
    ]
