# Generated by Django 3.2.7 on 2021-09-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20210912_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reputazione',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='thread',
            name='periodo',
            field=models.CharField(choices=[('Terzo anno', 'Terzo anno'), ('Facoltativi', 'Facoltativi'), ('Secondo anno', 'Secondo anno'), ('Primo anno', 'Primo anno')], default='Primo anno', max_length=100),
        ),
    ]
