# Generated by Django 3.2.7 on 2021-09-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20210912_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='periodo',
            field=models.CharField(choices=[('Primo anno', 'Primo anno'), ('Facoltativi', 'Facoltativi'), ('Secondo anno', 'Secondo anno'), ('Terzo anno', 'Terzo anno')], default='Primo anno', max_length=100),
        ),
    ]
